// 閉集合の固有名詞テーブル。駅・エリア・チェーンの英語表記はここが単一正本。
// 店固有の文字列（店名・施設・時間・highlights・notice・コース名）は各データの en フィールドに持つ。

export const STATION_EN: Record<string, string> = {
  たまプラーザ: 'Tamaplaza',
  みなとみらい: 'Minatomirai',
  上野: 'Ueno',
  上野毛: 'Kaminoge',
  中目黒: 'Nakameguro',
  亀戸: 'Kameido',
  京急川崎: 'Keikyu Kawasaki',
  保谷: 'Hoya',
  八王子: 'Hachioji',
  北千住: 'Kitasenju',
  千歳船橋: 'Chitose-funabashi',
  原当麻: 'Harataima',
  吉祥寺: 'Kichijoji',
  国分寺: 'Kokubunji',
  大塚: 'Otsuka',
  大森: 'Omori',
  川崎: 'Kawasaki',
  布田: 'Fuda',
  府中: 'Fuchu',
  御徒町: 'Okachimachi',
  志村坂上: 'Shimura-sakaue',
  恵比寿: 'Ebisu',
  成城学園前: 'Seijogakuen-mae',
  押上: 'Oshiage',
  表参道: 'Omotesando',
  新宿: 'Shinjuku',
  新宿三丁目: 'Shinjuku-sanchome',
  新宿西口: 'Shinjuku-nishiguchi',
  新百合ヶ丘: 'Shin-yurigaoka',
  明治神宮前: 'Meiji-jingumae',
  有楽町: 'Yurakucho',
  本厚木: 'Hon-atsugi',
  本郷台: 'Hongodai',
  東京テレポート: 'Tokyo Teleport',
  柴崎体育館: 'Shibasaki-taikukan',
  桜新町: 'Sakura-shinmachi',
  桜木町: 'Sakuragicho',
  梶が谷: 'Kajigaya',
  横浜: 'Yokohama',
  武蔵中原: 'Musashi-nakahara',
  池袋: 'Ikebukuro',
  浅草: 'Asakusa',
  海老名: 'Ebina',
  渋谷: 'Shibuya',
  港町: 'Minatomachi',
  湘南台: 'Shonandai',
  溝の口: 'Mizonokuchi',
  町田: 'Machida',
  相原: 'Aihara',
  相模大野: 'Sagami-ono',
  秋葉原: 'Akihabara',
  立川: 'Tachikawa',
  綾瀬: 'Ayase',
  聖蹟桜ヶ丘: 'Seiseki-sakuragaoka',
  自由が丘: 'Jiyugaoka',
  葛西: 'Kasai',
  藤沢: 'Fujisawa',
  辻堂: 'Tsujido',
  都庁前: 'Tochomae',
  銀座: 'Ginza',
  東銀座: 'Higashi-ginza',
  錦糸町: 'Kinshicho',
  関内: 'Kannai',
  青葉台: 'Aobadai',
  高田馬場: 'Takadanobaba',
  神保町: 'Jimbocho',
  鷺沼: 'Saginuma',
  水道橋: 'Suidobashi',
  大井町: 'Oimachi',
  三鷹: 'Mitaka',
};

export const AREA_EN: Record<string, string> = {
  お台場: 'Odaiba',
  たまプラーザ: 'Tamaplaza',
  みなとみらい: 'Minatomirai',
  上野毛: 'Kaminoge',
  亀戸: 'Kameido',
  保谷: 'Hoya',
  八王子: 'Hachioji',
  北千住: 'Kitasenju',
  厚木: 'Atsugi',
  原当麻: 'Harataima',
  吉祥寺: 'Kichijoji',
  国分寺: 'Kokubunji',
  大塚: 'Otsuka',
  大森: 'Omori',
  宮前平: 'Miyamaedaira',
  川崎: 'Kawasaki',
  布田: 'Fuda',
  府中: 'Fuchu',
  御徒町: 'Okachimachi',
  志村: 'Shimura',
  恵比寿: 'Ebisu',
  成城: 'Seijo',
  押上: 'Oshiage',
  新宿: 'Shinjuku',
  新百合ヶ丘: 'Shin-yurigaoka',
  本郷台: 'Hongodai',
  東葛西: 'Higashi-kasai',
  桜新町: 'Sakura-shinmachi',
  梶が谷: 'Kajigaya',
  横浜: 'Yokohama',
  池袋: 'Ikebukuro',
  '浅草・上野': 'Asakusa & Ueno',
  海老名: 'Ebina',
  '渋谷・原宿': 'Shibuya & Harajuku',
  溝の口: 'Mizonokuchi',
  町田: 'Machida',
  目黒: 'Meguro',
  相模大野: 'Sagami-ono',
  秋葉原: 'Akihabara',
  立川: 'Tachikawa',
  綾瀬: 'Ayase',
  聖蹟桜ヶ丘: 'Seiseki-sakuragaoka',
  自由が丘: 'Jiyugaoka',
  芦花公園: 'Roka-koen',
  藤沢: 'Fujisawa',
  辻堂: 'Tsujido',
  '銀座・有楽町': 'Ginza & Yurakucho',
  銀座: 'Ginza',
  神保町: 'Jimbocho',
  錦糸町: 'Kinshicho',
  関内: 'Kannai',
  青葉台: 'Aobadai',
  高津: 'Takatsu',
  高田馬場: 'Takadanobaba',
  水道橋: 'Suidobashi',
  大井町: 'Oimachi',
  三鷹: 'Mitaka',
};

export const CHAIN_EN: Record<string, string> = {
  きづなすし: 'Kizuna Sushi',
  しゃぶしゃぶ温野菜: 'Shabu-shabu Onyasai',
  しゃぶ葉: 'Shabu-yo',
  すたみな太郎: 'Stamina Taro',
  まいた: 'Maita',
  ゆず庵: 'Yuzu-an',
  シェーキーズ: "Shakey's",
  シズラー: 'Sizzler',
  スイーツパラダイス: 'Sweets Paradise',
  ビッグボーイ: 'Big Boy',
  ベーカリーレストランサンマルク: 'Bakery Restaurant Saint Marc',
  モーモーパラダイス: 'Mo-mo Paradise',
  ラ・パウザ: 'La Pausa',
  レストランスエヒロ館: 'Restaurant Suehirokan',
  串家物語: 'Kushiya Monogatari',
  焼肉きんぐ: 'Yakiniku King',
  牛物語: 'Ushi Monogatari',
  牛角: 'Gyu-kaku',
  神戸屋キッチン: 'Kobeya Kitchen',
  神戸屋レストラン: 'Kobeya Restaurant',
  肉ヤロー: 'Niku Yaro',
  道とん堀: 'Dotonbori',
  雛鮨: 'Hina-zushi',
  鳥物語: 'Tori Monogatari',
  蔵部: 'Kurabu',
  酢重ダイニング: 'Suju Dining',
  佳照庵: 'Kasho-an',
  '洋食屋 伊勢十': 'Yousyokuya Iseju',
  '和の菜彩 さとう': 'Wa no Saisai Satou',
  'まぐろ相馬水産': 'Maguro Souma Suisan',
  やよい軒: 'Yayoiken',
  ねぎし: 'Negishi',
  とんかつ和幸: 'Tonkatsu Wako',
  とんかつ新宿さぼてん: 'Tonkatsu Shinjuku Saboten',
  '大かまど飯 寅福': 'Okamado-meshi Torafuku',
  'とんかつ まい泉': 'Tonkatsu Maisen',
};
